server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

security:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
